import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { DatabaseSchema } from "./types.ts";

function typeName(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

export function generateTypes(schema: DatabaseSchema): string {
  const lines = ["// Generated by SHQL. Do not edit manually.", ""];
  for (const table of schema.tables.values()) {
    lines.push(`export interface ${typeName(table.name)} {`);
    for (const column of table.columns) {
      const base =
        column.type === "number"
          ? "number"
          : column.type === "boolean"
            ? "boolean"
            : column.type === "date" || column.type === "datetime"
              ? "Date"
              : "string";
      lines.push(`  ${JSON.stringify(column.name)}: ${base}${column.nullable ? " | null" : ""};`);
    }
    lines.push("}", "");
  }
  lines.push("export interface ShqlTables {");
  for (const table of schema.tables.values())
    lines.push(`  ${JSON.stringify(table.name)}: ${typeName(table.name)};`);
  lines.push("}", "");
  return `${lines.join("\n")}\n`;
}

export async function writeTypes(schema: DatabaseSchema, path: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, generateTypes(schema), "utf8");
}
